import type { IconType } from "@/components/IconLayer";

export const FILTER_MAP: Record<string, IconType[]> = {
  Restrooms: ["restroom"],
  "Study Rooms": ["studyroom"],
  "Vending Machines": ["vending"],
  "Water Fountains": ["fountain", "bottle"],
  Elevators: ["elevator"],
  "Emergency Exits": ["emergency"],
  "Fire Extinguishers": ["fire"],
  Defibrillators: ["defib"],
};

// Maps search keywords → filter label (must match FILTER_MAP keys exactly)
export const SEARCH_ALIAS_MAP: Record<string, string> = {
  restroom: "Restrooms",
  restrooms: "Restrooms",
  bathroom: "Restrooms",
  bathrooms: "Restrooms",
  toilet: "Restrooms",
  toilets: "Restrooms",
  "study room": "Study Rooms",
  "study rooms": "Study Rooms",
  studyroom: "Study Rooms",
  studyrooms: "Study Rooms",
  study: "Study Rooms",
  vending: "Vending Machines",
  "vending machine": "Vending Machines",
  "vending machines": "Vending Machines",
  snacks: "Vending Machines",
  "water fountain": "Water Fountains",
  "water fountains": "Water Fountains",
  fountain: "Water Fountains",
  fountains: "Water Fountains",
  "bottle filling": "Water Fountains",
  water: "Water Fountains",
  elevator: "Elevators",
  elevators: "Elevators",
  lift: "Elevators",
  "emergency exit": "Emergency Exits",
  "emergency exits": "Emergency Exits",
  emergency: "Emergency Exits",
  exit: "Emergency Exits",
  exits: "Emergency Exits",
  "fire extinguisher": "Fire Extinguishers",
  "fire extinguishers": "Fire Extinguishers",
  fire: "Fire Extinguishers",
  extinguisher: "Fire Extinguishers",
  extinguishers: "Fire Extinguishers",
  defibrillator: "Defibrillators",
  defibrillators: "Defibrillators",
  defib: "Defibrillators",
  aed: "Defibrillators",
  "first aid": "Defibrillators",
};