 // navigation/seed-edges.ts
 // All edges for PFT (floor 1).

import type { NavNode, NavEdge } from './db';

type RawEdge = Omit<NavEdge, 'cost'>;

const FLOOR_TRANSITION_COST = 15;

export const RAW_EDGES: RawEdge[] = [

    // FLOOR 1 - ROW 0
    { id: 'hw0.10_lb1146a',  fromNodeId: 'hallway_0.10', toNodeId: 'lab_1146_a',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.10_hw0.11',   fromNodeId: 'hallway_0.10', toNodeId: 'hallway_0.11',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.11_hw0.12',   fromNodeId: 'hallway_0.11', toNodeId: 'hallway_0.12',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.11_lb1154c',  fromNodeId: 'hallway_0.11', toNodeId: 'lab_1154_c',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.12_hw0.13',   fromNodeId: 'hallway_0.12', toNodeId: 'hallway_0.13',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.13_hw0.14',   fromNodeId: 'hallway_0.13', toNodeId: 'hallway_0.14',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.14_hw0.15',   fromNodeId: 'hallway_0.14', toNodeId: 'hallway_0.15',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.15_cr1221a',  fromNodeId: 'hallway_0.15', toNodeId: 'room_1221_a',     type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.15_cr1218a',  fromNodeId: 'hallway_0.15', toNodeId: 'room_1218_a',     type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.15_hw0.16',   fromNodeId: 'hallway_0.15', toNodeId: 'hallway_0.16',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.16_cr1221b',  fromNodeId: 'hallway_0.16', toNodeId: 'room_1221_b',     type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.16_hw0.17',   fromNodeId: 'hallway_0.16', toNodeId: 'hallway_0.17',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.17_cr1225a',  fromNodeId: 'hallway_0.17', toNodeId: 'room_1225_a',     type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.17_hw0.18',   fromNodeId: 'hallway_0.17', toNodeId: 'hallway_0.18',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.18_cr1225b',  fromNodeId: 'hallway_0.18', toNodeId: 'room_1225_b',     type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.18_hw0.19',   fromNodeId: 'hallway_0.18', toNodeId: 'hallway_0.19',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.19_br0',      fromNodeId: 'hallway_0.19', toNodeId: 'bathroom_0',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.19_ft0',      fromNodeId: 'hallway_0.19', toNodeId: 'fountain_0',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.19_hw0.20',   fromNodeId: 'hallway_0.19', toNodeId: 'hallway_0.20',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.20_hw0.21',   fromNodeId: 'hallway_0.20', toNodeId: 'hallway_0.21',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.21_hw0.22',   fromNodeId: 'hallway_0.21', toNodeId: 'hallway_0.22',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.22_hw0.23',   fromNodeId: 'hallway_0.22', toNodeId: 'hallway_0.23',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.23_br1',      fromNodeId: 'hallway_0.23', toNodeId: 'bathroom_1',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.23_hw0.24',   fromNodeId: 'hallway_0.23', toNodeId: 'hallway_0.24',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.24_hw0.30',   fromNodeId: 'hallway_0.24', toNodeId: 'hallway_0.30',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.30_lb1364a',  fromNodeId: 'hallway_0.30', toNodeId: 'lab_1364_a',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.30_hw0.25',   fromNodeId: 'hallway_0.30', toNodeId: 'hallway_0.25',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.25_lb1367a',  fromNodeId: 'hallway_0.25', toNodeId: 'lab_1367_a',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.25_hw0.26',   fromNodeId: 'hallway_0.25', toNodeId: 'hallway_0.26',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.26_lb1366a',  fromNodeId: 'hallway_0.26', toNodeId: 'lab_1366_a',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.26_hw0.27',   fromNodeId: 'hallway_0.26', toNodeId: 'hallway_0.27',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.27_lb1368a',  fromNodeId: 'hallway_0.27', toNodeId: 'lab_1368_a',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw0.27_hw0.28',   fromNodeId: 'hallway_0.27', toNodeId: 'hallway_0.28',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.28_st1',      fromNodeId: 'hallway_0.28', toNodeId: 'stairs_1',        type: 'hallway', accessible: false, bidirectional: true },
    { id: 'hw0.28_en3',      fromNodeId: 'hallway_0.28', toNodeId: 'entrance_3',      type: 'hallway', accessible: true,  bidirectional: true },

    // FLOOR 1 - ROW 1
    { id: 'en12_hw1.0',      fromNodeId: 'entrance_12',    toNodeId: 'hallway_1.0',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.0_lb1124a',   fromNodeId: 'hallway_1.0',    toNodeId: 'lab_1124_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.0_hw1.10',    fromNodeId: 'hallway_1.0',    toNodeId: 'hallway_1.10',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.10_hw1.11',   fromNodeId: 'hallway_1.10',   toNodeId: 'hallway_1.11',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.11_lb1122a',  fromNodeId: 'hallway_1.11',   toNodeId: 'lab_1122_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.11_hw1.12',   fromNodeId: 'hallway_1.11',   toNodeId: 'hallway_1.12',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.12_lb1120a',  fromNodeId: 'hallway_1.12',   toNodeId: 'lab_1120_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.12_br4',      fromNodeId: 'hallway_1.12',   toNodeId: 'bathroom_4',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.12_ft1',      fromNodeId: 'hallway_1.12',   toNodeId: 'fountain_1',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.12_hw1.13',   fromNodeId: 'hallway_1.12',   toNodeId: 'hallway_1.13',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.13_ev1',      fromNodeId: 'hallway_1.13',   toNodeId: 'elevator_1',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.13_hw1.14',   fromNodeId: 'hallway_1.13',   toNodeId: 'hallway_1.14',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.14_v0',       fromNodeId: 'hallway_1.14',   toNodeId: 'vending_0',     type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.14_lb1118a',  fromNodeId: 'hallway_1.14',   toNodeId: 'lab_1118_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.14_hw1.15',   fromNodeId: 'hallway_1.14',   toNodeId: 'hallway_1.15',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.15_hw1.16',   fromNodeId: 'hallway_1.15',   toNodeId: 'hallway_1.16',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.16_cr1253a',  fromNodeId: 'hallway_1.16',   toNodeId: 'room_1253_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.16_hw1.17',   fromNodeId: 'hallway_1.16',   toNodeId: 'hallway_1.17',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.17_cr1256a',  fromNodeId: 'hallway_1.17',   toNodeId: 'room_1256_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.17_hw1.18',   fromNodeId: 'hallway_1.17',   toNodeId: 'hallway_1.18',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.18_cr1253b',  fromNodeId: 'hallway_1.18',   toNodeId: 'room_1253_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.18_hw1.19',   fromNodeId: 'hallway_1.18',   toNodeId: 'hallway_1.19',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.19_cr1246b',  fromNodeId: 'hallway_1.19',   toNodeId: 'room_1246_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.19_hw1.20',   fromNodeId: 'hallway_1.19',   toNodeId: 'hallway_1.20',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.20_cr1256b',  fromNodeId: 'hallway_1.20',   toNodeId: 'room_1256_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.20_hw1.21',   fromNodeId: 'hallway_1.20',   toNodeId: 'hallway_1.21',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.21_hw1.22',   fromNodeId: 'hallway_1.21',   toNodeId: 'hallway_1.22',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.22_hw1.23',   fromNodeId: 'hallway_1.22',   toNodeId: 'hallway_1.23',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.23_hw1.24',   fromNodeId: 'hallway_1.23',   toNodeId: 'hallway_1.24',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.24_hw1.25',   fromNodeId: 'hallway_1.24',   toNodeId: 'hallway_1.25',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.25_hw1.26',   fromNodeId: 'hallway_1.25',   toNodeId: 'hallway_1.26',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.26_hw1.27',   fromNodeId: 'hallway_1.26',   toNodeId: 'hallway_1.27',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.27_hw1.28',   fromNodeId: 'hallway_1.27',   toNodeId: 'hallway_1.28',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.28_lb1327a',  fromNodeId: 'hallway_1.28',   toNodeId: 'lab_1327_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.28_hw1.29',   fromNodeId: 'hallway_1.28',   toNodeId: 'hallway_1.29',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.29_lb1329a',  fromNodeId: 'hallway_1.29',   toNodeId: 'lab_1329_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.29_hw1.30',   fromNodeId: 'hallway_1.29',   toNodeId: 'hallway_1.30',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.30_hw1.31',   fromNodeId: 'hallway_1.30',   toNodeId: 'hallway_1.31',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.31_lb1330a',  fromNodeId: 'hallway_1.31',   toNodeId: 'lab_1330_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.31_hw1.32',   fromNodeId: 'hallway_1.31',   toNodeId: 'hallway_1.32',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.32_lb1331a',  fromNodeId: 'hallway_1.32',   toNodeId: 'lab_1331_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.32_hw1.33',   fromNodeId: 'hallway_1.32',   toNodeId: 'hallway_1.33',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.33_hwF6',     fromNodeId: 'hallway_1.33',   toNodeId: 'hallwayF_6',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw1.33_en5',      fromNodeId: 'hallway_1.33',   toNodeId: 'entrance_5',    type: 'door',    accessible: true,  bidirectional: true },

    // FLOOR 1 - ROW 2
    { id: 'en11_hw2.0',      fromNodeId: 'entrance_11',    toNodeId: 'hallway_2.0',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.0_hw2.10',    fromNodeId: 'hallway_2.0',    toNodeId: 'hallway_2.10',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.10_hw2.11',   fromNodeId: 'hallway_2.10',   toNodeId: 'hallway_2.11',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.11_hw2.12',   fromNodeId: 'hallway_2.11',   toNodeId: 'hallway_2.12',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.12_hw2.13',   fromNodeId: 'hallway_2.12',   toNodeId: 'hallway_2.13',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.13_hw2.14',   fromNodeId: 'hallway_2.13',   toNodeId: 'hallway_2.14',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.14_hw2.15',   fromNodeId: 'hallway_2.14',   toNodeId: 'hallway_2.15',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.15_hw2.16',   fromNodeId: 'hallway_2.15',   toNodeId: 'hallway_2.16',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.16_hw2.17',   fromNodeId: 'hallway_2.16',   toNodeId: 'hallway_2.17',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.17_hw2.18',   fromNodeId: 'hallway_2.17',   toNodeId: 'hallway_2.18',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.18_hw2.19',   fromNodeId: 'hallway_2.18',   toNodeId: 'hallway_2.19',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.19_hw2.20',   fromNodeId: 'hallway_2.19',   toNodeId: 'hallway_2.20',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.20_hw2.21',   fromNodeId: 'hallway_2.20',   toNodeId: 'hallway_2.21',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.21_hw2.22',   fromNodeId: 'hallway_2.21',   toNodeId: 'hallway_2.22',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.22_hw2.23',   fromNodeId: 'hallway_2.22',   toNodeId: 'hallway_2.23',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.23_en6',      fromNodeId: 'hallway_2.23',   toNodeId: 'entrance_6',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.10_cr1124b',  fromNodeId: 'hallway_2.10',   toNodeId: 'room_1124_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw2.11_lb1112b',  fromNodeId: 'hallway_2.11',   toNodeId: 'lab_1112_b',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw2.12_lb1108a',  fromNodeId: 'hallway_2.12',   toNodeId: 'lab_1108_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw2.14_str6',     fromNodeId: 'hallway_2.14',   toNodeId: 'stairs_6',      type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.15_cr1263a',  fromNodeId: 'hallway_2.15',   toNodeId: 'room_1263_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw2.16_cr1263b',  fromNodeId: 'hallway_2.16',   toNodeId: 'room_1263_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw2.17_cr1202b',  fromNodeId: 'hallway_2.17',   toNodeId: 'room_1202_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw2.21_lb1300a',  fromNodeId: 'hallway_2.21',   toNodeId: 'lab_1300_a',    type: 'door',    accessible: true,  bidirectional: true },

    // FLOOR 1 - ROW 3
    { id: 'hw3.0_hw3.10',    fromNodeId: 'hallway_3.0',    toNodeId: 'hallway_3.10',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw3.10_hw3.11',   fromNodeId: 'hallway_3.10',   toNodeId: 'hallway_3.11',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw3.11_hw3.12',   fromNodeId: 'hallway_3.11',   toNodeId: 'hallway_3.12',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw3.12_en4',      fromNodeId: 'hallway_3.12',   toNodeId: 'entrance_4',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw3.10_lb1355a',  fromNodeId: 'hallway_3.10',   toNodeId: 'lab_1355_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw3.10_lb1356a',  fromNodeId: 'hallway_3.10',   toNodeId: 'lab_1356_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw3.11_lb1358a',  fromNodeId: 'hallway_3.11',   toNodeId: 'lab_1358_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hw3.12_lb1357a',  fromNodeId: 'hallway_3.12',   toNodeId: 'lab_1357_a',    type: 'door',    accessible: true,  bidirectional: true },

    // FLOOR 1 - COLUMN A
    { id: 'hw0.10_hwA1',     fromNodeId: 'hallway_0.10',   toNodeId: 'hallwayA_1',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA1_hwA2',       fromNodeId: 'hallwayA_1',     toNodeId: 'hallwayA_2',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA2_hwA3',       fromNodeId: 'hallwayA_2',     toNodeId: 'hallwayA_3',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA3_hwA4',       fromNodeId: 'hallwayA_3',     toNodeId: 'hallwayA_4',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA4_hwA5',       fromNodeId: 'hallwayA_4',     toNodeId: 'hallwayA_5',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA5_hwA6',       fromNodeId: 'hallwayA_5',     toNodeId: 'hallwayA_6',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA6_hwA7',       fromNodeId: 'hallwayA_6',     toNodeId: 'hallwayA_7',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA7_hwA8',       fromNodeId: 'hallwayA_7',     toNodeId: 'hallwayA_8',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA8_hwA9',       fromNodeId: 'hallwayA_8',     toNodeId: 'hallwayA_9',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA9_hwA11',      fromNodeId: 'hallwayA_9',     toNodeId: 'hallwayA_11',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA11_hw1.10',    fromNodeId: 'hallwayA_11',    toNodeId: 'hallway_1.10',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.0_hwA12',     fromNodeId: 'hallway_2.0',    toNodeId: 'hallwayA_12',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA12_hwA13',     fromNodeId: 'hallwayA_12',    toNodeId: 'hallwayA_13',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA13_st5',       fromNodeId: 'hallwayA_13',    toNodeId: 'stairs_5',      type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwA1_lb1147a',    fromNodeId: 'hallwayA_1',     toNodeId: 'lab_1147_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA2_lb1146b',    fromNodeId: 'hallwayA_2',     toNodeId: 'lab_1146_b',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA3_lb1144a',    fromNodeId: 'hallwayA_3',     toNodeId: 'lab_1144_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA4_lb1138a',    fromNodeId: 'hallwayA_4',     toNodeId: 'lab_1138_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA5_lb1130a',    fromNodeId: 'hallwayA_5',     toNodeId: 'lab_1130_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA6_lb1133b',    fromNodeId: 'hallwayA_6',     toNodeId: 'lab_1133_b',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA7_lb1131b',    fromNodeId: 'hallwayA_7',     toNodeId: 'lab_1131_b',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA8_lb1130b',    fromNodeId: 'hallwayA_8',     toNodeId: 'lab_1130_b',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA9_lb1126a',    fromNodeId: 'hallwayA_9',     toNodeId: 'lab_1126_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwA11_lb1126b',   fromNodeId: 'hallwayA_11',    toNodeId: 'lab_1126_b',    type: 'door',    accessible: true,  bidirectional: true },

    // FLOOR 1 - COLUMN B
    { id: 'en0_hw0.13',      fromNodeId: 'entrance_0',     toNodeId: 'hallway_0.13',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.13_hwB1',     fromNodeId: 'hallway_0.13',   toNodeId: 'hallwayB_1',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB1_lb1154a',    fromNodeId: 'hallwayB_1',     toNodeId: 'lab_1154_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB1_hwB2',       fromNodeId: 'hallwayB_1',     toNodeId: 'hallwayB_2',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB2_cr1218b',    fromNodeId: 'hallwayB_2',     toNodeId: 'room_1218_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB2_hwB3',       fromNodeId: 'hallwayB_2',     toNodeId: 'hallwayB_3',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB3_cr1216a',    fromNodeId: 'hallwayB_3',     toNodeId: 'room_1216_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB3_hwB4',       fromNodeId: 'hallwayB_3',     toNodeId: 'hallwayB_4',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB4_lb1154b',    fromNodeId: 'hallwayB_4',     toNodeId: 'lab_1154_b',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB4_hwB5',       fromNodeId: 'hallwayB_4',     toNodeId: 'hallwayB_5',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB5_lb1139a',    fromNodeId: 'hallwayB_5',     toNodeId: 'lab_1139_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB5_hwB6',       fromNodeId: 'hallwayB_5',     toNodeId: 'hallwayB_6',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB6_cr1212a',    fromNodeId: 'hallwayB_6',     toNodeId: 'room_1212_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB6_hwB7',       fromNodeId: 'hallwayB_6',     toNodeId: 'hallwayB_7',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB7_lb1133a',    fromNodeId: 'hallwayB_7',     toNodeId: 'lab_1133_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB7_hwB8',       fromNodeId: 'hallwayB_7',     toNodeId: 'hallwayB_8',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB8_lb1131a',    fromNodeId: 'hallwayB_8',     toNodeId: 'lab_1131_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB8_hwB9',       fromNodeId: 'hallwayB_8',     toNodeId: 'hallwayB_9',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB9_cr1212b',    fromNodeId: 'hallwayB_9',     toNodeId: 'room_1212_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB9_hw1.15',     fromNodeId: 'hallwayB_9',     toNodeId: 'hallway_1.15',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.15_hwB11',    fromNodeId: 'hallway_1.15',   toNodeId: 'hallwayB_11',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB11_hwB12',     fromNodeId: 'hallwayB_11',    toNodeId: 'hallwayB_12',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB12_lb1114a',   fromNodeId: 'hallwayB_12',    toNodeId: 'lab_1114_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB12_hwB13',     fromNodeId: 'hallwayB_12',    toNodeId: 'hallwayB_13',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB13_cr1206a',   fromNodeId: 'hallwayB_13',    toNodeId: 'room_1206_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB13_hwB14',     fromNodeId: 'hallwayB_13',    toNodeId: 'hallwayB_14',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB14_cr1206b',   fromNodeId: 'hallwayB_14',    toNodeId: 'room_1206_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB14_hwB15',     fromNodeId: 'hallwayB_14',    toNodeId: 'hallwayB_15',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB15_lb1114b',   fromNodeId: 'hallwayB_15',    toNodeId: 'lab_1114_b',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB15_hwB16',     fromNodeId: 'hallwayB_15',    toNodeId: 'hallwayB_16',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB16_lb1112a',   fromNodeId: 'hallwayB_16',    toNodeId: 'lab_1112_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB16_hw2.13',    fromNodeId: 'hallwayB_16',    toNodeId: 'hallway_2.13',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.13_hwB17',    fromNodeId: 'hallway_2.13',   toNodeId: 'hallwayB_17',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB17_cr1202a',   fromNodeId: 'hallwayB_17',    toNodeId: 'room_1202_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB17_hwB18',     fromNodeId: 'hallwayB_17',    toNodeId: 'hallwayB_18',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB18_br5',       fromNodeId: 'hallwayB_18',    toNodeId: 'bathroom_5',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB18_hwB19',     fromNodeId: 'hallwayB_18',    toNodeId: 'hallwayB_19',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB19_cr1100a',   fromNodeId: 'hallwayB_19',    toNodeId: 'room_1100_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB19_hwB20',     fromNodeId: 'hallwayB_19',    toNodeId: 'hallwayB_20',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwB20_cr1200a',   fromNodeId: 'hallwayB_20',    toNodeId: 'room_1200_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwB20_en10',      fromNodeId: 'hallwayB_20',    toNodeId: 'entrance_10',   type: 'hallway', accessible: true,  bidirectional: true },

    // FLOOR 1 - COLUMN C
    { id: 'hw0.18_hwC1',     fromNodeId: 'hallway_0.18',   toNodeId: 'hallwayC_1',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC1_hwC2',       fromNodeId: 'hallwayC_1',     toNodeId: 'hallwayC_2',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC2_hwC3',       fromNodeId: 'hallwayC_2',     toNodeId: 'hallwayC_3',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC3_hwC4',       fromNodeId: 'hallwayC_3',     toNodeId: 'hallwayC_4',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC4_hwC5',       fromNodeId: 'hallwayC_4',     toNodeId: 'hallwayC_5',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC5_hwC6',       fromNodeId: 'hallwayC_5',     toNodeId: 'hallwayC_6',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC6_hwC7',       fromNodeId: 'hallwayC_6',     toNodeId: 'hallwayC_7',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC7_hwC8',       fromNodeId: 'hallwayC_7',     toNodeId: 'hallwayC_8',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC8_hwC9',       fromNodeId: 'hallwayC_8',     toNodeId: 'hallwayC_9',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC9_hwC11',      fromNodeId: 'hallwayC_9',     toNodeId: 'hallwayC_11',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC11_hwC12',     fromNodeId: 'hallwayC_11',    toNodeId: 'hallwayC_12',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC12_hwC13',     fromNodeId: 'hallwayC_12',    toNodeId: 'hallwayC_13',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC13_hw1.21',    fromNodeId: 'hallwayC_13',    toNodeId: 'hallway_1.21',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.21_hwC14',    fromNodeId: 'hallway_1.21',   toNodeId: 'hallwayC_14',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC14_hwC15',     fromNodeId: 'hallwayC_14',    toNodeId: 'hallwayC_15',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC15_hwC16',     fromNodeId: 'hallwayC_15',    toNodeId: 'hallwayC_16',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC16_hwC17',     fromNodeId: 'hallwayC_16',    toNodeId: 'hallwayC_17',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC17_hw2.18',    fromNodeId: 'hallwayC_17',    toNodeId: 'hallway_2.18',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.18_hwC18',    fromNodeId: 'hallway_2.18',   toNodeId: 'hallwayC_18',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC18_hwC19',     fromNodeId: 'hallwayC_18',    toNodeId: 'hallwayC_19',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC19_en9',       fromNodeId: 'hallwayC_19',    toNodeId: 'entrance_9',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwC1_cr1232a',    fromNodeId: 'hallwayC_1',     toNodeId: 'room_1232_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC2_cr1233a',    fromNodeId: 'hallwayC_2',     toNodeId: 'room_1233_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC3_cr1232b',    fromNodeId: 'hallwayC_3',     toNodeId: 'room_1232_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC4_cr1236a',    fromNodeId: 'hallwayC_4',     toNodeId: 'room_1236_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC5_lb1237a',    fromNodeId: 'hallwayC_5',     toNodeId: 'lab_1237_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC6_cr1236b',    fromNodeId: 'hallwayC_6',     toNodeId: 'room_1236_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC7_cr1240a',    fromNodeId: 'hallwayC_7',     toNodeId: 'room_1240_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC8_cr1240b',    fromNodeId: 'hallwayC_8',     toNodeId: 'room_1240_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC9_cr1244a',    fromNodeId: 'hallwayC_9',     toNodeId: 'room_1244_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC11_cr1246a',   fromNodeId: 'hallwayC_11',    toNodeId: 'room_1246_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC12_cr1245a',   fromNodeId: 'hallwayC_12',    toNodeId: 'room_1245_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC13_br3',       fromNodeId: 'hallwayC_13',    toNodeId: 'bathroom_3',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC14_cr1258a',   fromNodeId: 'hallwayC_14',    toNodeId: 'room_1258_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC15_cr1258b',   fromNodeId: 'hallwayC_15',    toNodeId: 'room_1258_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC16_cr1262a',   fromNodeId: 'hallwayC_16',    toNodeId: 'room_1262_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC18_cr1200b',   fromNodeId: 'hallwayC_18',    toNodeId: 'room_1200_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwC19_st4',       fromNodeId: 'hallwayC_19',    toNodeId: 'stairs_4',      type: 'door',    accessible: true,  bidirectional: true },

    // FLOOR 1 - COLUMN D
    { id: 'en1_hwD1',        fromNodeId: 'entrance_1',     toNodeId: 'hallwayD_1',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'en2_hwD1',        fromNodeId: 'entrance_2',     toNodeId: 'hallwayD_1',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD1_hwD2',       fromNodeId: 'hallwayD_1',     toNodeId: 'hallwayD_2',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD2_hw0.21',     fromNodeId: 'hallwayD_2',     toNodeId: 'hallway_0.21',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.21_hwD3',     fromNodeId: 'hallway_0.21',   toNodeId: 'hallwayD_3',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD3_hwD4',       fromNodeId: 'hallwayD_3',     toNodeId: 'hallwayD_4',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD3_hwD5',       fromNodeId: 'hallwayD_3',     toNodeId: 'hallwayD_5',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD5_hwD6',       fromNodeId: 'hallwayD_5',     toNodeId: 'hallwayD_6',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD6_hwD7',       fromNodeId: 'hallwayD_6',     toNodeId: 'hallwayD_7',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD7_hw1.24',     fromNodeId: 'hallwayD_7',     toNodeId: 'hallway_1.24',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.23_hwD8',     fromNodeId: 'hallway_1.23',   toNodeId: 'hallwayD_8',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD8_hwD9',       fromNodeId: 'hallwayD_8',     toNodeId: 'hallwayD_9',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD9_hwD11',      fromNodeId: 'hallwayD_9',     toNodeId: 'hallwayD_11',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD11_hwD12',     fromNodeId: 'hallwayD_11',    toNodeId: 'hallwayD_12',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD12_hw2.19',    fromNodeId: 'hallwayD_12',    toNodeId: 'hallway_2.19',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD12_hwD15',     fromNodeId: 'hallwayD_12',    toNodeId: 'hallwayD_15',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD15_hw2.20',    fromNodeId: 'hallwayD_15',    toNodeId: 'hallway_2.20',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD9_hwD13',      fromNodeId: 'hallwayD_9',     toNodeId: 'hallwayD_13',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD13_hwD14',     fromNodeId: 'hallwayD_13',    toNodeId: 'hallwayD_14',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD14_hwD19',     fromNodeId: 'hallwayD_14',    toNodeId: 'hallwayD_19',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD18_hwD19',     fromNodeId: 'hallwayD_18',    toNodeId: 'hallwayD_19',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD18_hwD20',     fromNodeId: 'hallwayD_18',    toNodeId: 'hallwayD_20',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD20_hwD21',     fromNodeId: 'hallwayD_20',    toNodeId: 'hallwayD_21',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD21_hw2.21',    fromNodeId: 'hallwayD_21',    toNodeId: 'hallway_2.21',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD15_hwD21',     fromNodeId: 'hallwayD_15',    toNodeId: 'hallwayD_21',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.20_hwD16',    fromNodeId: 'hallway_2.20',   toNodeId: 'hallwayD_16',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.25_hwD17',    fromNodeId: 'hallway_1.25',   toNodeId: 'hallwayD_17',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD17_hwD18',     fromNodeId: 'hallwayD_17',    toNodeId: 'hallwayD_18',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD14_hwD15',     fromNodeId: 'hallwayD_14',    toNodeId: 'hallwayD_15',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD16_en8',       fromNodeId: 'hallwayD_16',    toNodeId: 'entrance_8',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD4_st9',        fromNodeId: 'hallwayD_4',     toNodeId: 'stairs_9',      type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwD6_cr1245b',    fromNodeId: 'hallwayD_6',     toNodeId: 'room_1245_b',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwD6_lb1350a',    fromNodeId: 'hallwayD_6',     toNodeId: 'lab_1350_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwD7_ev0',        fromNodeId: 'hallwayD_7',     toNodeId: 'elevator_0',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwD13_st7',       fromNodeId: 'hallwayD_13',    toNodeId: 'stairs_7',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwD19_st8',       fromNodeId: 'hallwayD_19',    toNodeId: 'stairs_8',      type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwD16_lb1300b',   fromNodeId: 'hallwayD_16',    toNodeId: 'lab_1300_b',    type: 'door',    accessible: true,  bidirectional: true },

    // FLOOR 1 - COLUMN E
    { id: 'hwE1_hw0.24',     fromNodeId: 'hallwayE_1',     toNodeId: 'hallway_0.24',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw0.24_hwE2',     fromNodeId: 'hallway_0.24',   toNodeId: 'hallwayE_2',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE2_hw3.0',      fromNodeId: 'hallwayE_2',     toNodeId: 'hallway_3.0',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw3.0_hwE3',      fromNodeId: 'hallway_3.0',    toNodeId: 'hallwayE_3',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE3_hwE4',       fromNodeId: 'hallwayE_3',     toNodeId: 'hallwayE_4',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE4_hwE5',       fromNodeId: 'hallwayE_4',     toNodeId: 'hallwayE_5',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE5_hw1.27',     fromNodeId: 'hallwayE_5',     toNodeId: 'hallway_1.27',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw1.27_hwE6',     fromNodeId: 'hallway_1.27',   toNodeId: 'hallwayE_6',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE6_hwE7',       fromNodeId: 'hallwayE_6',     toNodeId: 'hallwayE_7',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE7_hw2.22',     fromNodeId: 'hallwayE_7',     toNodeId: 'hallway_2.22',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.22_hwE8',     fromNodeId: 'hallway_2.22',   toNodeId: 'hallwayE_8',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE8_hwE9',       fromNodeId: 'hallwayE_8',     toNodeId: 'hallwayE_9',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE9_hwE11',      fromNodeId: 'hallwayE_9',     toNodeId: 'hallwayE_11',   type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE11_en7',       fromNodeId: 'hallwayE_11',    toNodeId: 'entrance_7',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE1_ev2',        fromNodeId: 'hallwayE_1',     toNodeId: 'elevator_2',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwE2_cr1360a',    fromNodeId: 'hallwayE_2',     toNodeId: 'room_1360_a',   type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwE3_lb1354a',    fromNodeId: 'hallwayE_3',     toNodeId: 'lab_1354_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwE4_lb1350b',    fromNodeId: 'hallwayE_4',     toNodeId: 'lab_1350_b',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwE5_br2',        fromNodeId: 'hallwayE_5',     toNodeId: 'bathroom_2',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwE9_lb1100a',    fromNodeId: 'hallwayE_9',     toNodeId: 'lab_1100_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwE11_st3',       fromNodeId: 'hallwayE_11',    toNodeId: 'stairs_3',      type: 'hallway', accessible: true,  bidirectional: true },

    // FLOOR 1 - COLUMN F
    { id: 'hw1.30_hwF1',     fromNodeId: 'hallway_1.30',   toNodeId: 'hallwayF_1',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwF1_hwF2',       fromNodeId: 'hallwayF_1',     toNodeId: 'hallwayF_2',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwF2_hwF3',       fromNodeId: 'hallwayF_2',     toNodeId: 'hallwayF_3',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwF3_hw2.23',     fromNodeId: 'hallwayF_3',     toNodeId: 'hallway_2.23',  type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hw2.23_hwF4',     fromNodeId: 'hallway_2.23',   toNodeId: 'hallwayF_4',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwF4_hwF5',       fromNodeId: 'hallwayF_4',     toNodeId: 'hallwayF_5',    type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwF6_st2',        fromNodeId: 'hallwayF_6',     toNodeId: 'stairs_2',      type: 'hallway', accessible: true,  bidirectional: true },
    { id: 'hwF1_lb1325a',    fromNodeId: 'hallwayF_1',     toNodeId: 'lab_1325_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwF2_lb1324a',    fromNodeId: 'hallwayF_2',     toNodeId: 'lab_1324_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwF3_lb1322a',    fromNodeId: 'hallwayF_3',     toNodeId: 'lab_1322_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwF3_lb1323a',    fromNodeId: 'hallwayF_3',     toNodeId: 'lab_1323_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwF4_lb1321a',    fromNodeId: 'hallwayF_4',     toNodeId: 'lab_1321_a',    type: 'door',    accessible: true,  bidirectional: true },
    { id: 'hwF5_lb1317a',    fromNodeId: 'hallwayF_5',     toNodeId: 'lab_1317_a',    type: 'door',    accessible: true,  bidirectional: true },

];

// uses x and y coord to compute distance in ft
export function computeEdgeCosts(nodes: NavNode[]): NavEdge[] {
    const nodeMap = new Map(nodes.map(n => [n.id, n]));

    return RAW_EDGES.map(edge => {
        const from = nodeMap.get(edge.fromNodeId);
        const to   = nodeMap.get(edge.toNodeId);

        let cost: number;

        if (!from || !to) {
            console.warn(`[seed-edges] Missing node for edge "${edge.id}" (from: ${edge.fromNodeId}, to: ${edge.toNodeId})`);
            cost = 10;
        } else if (from.floor !== to.floor) {
            cost = FLOOR_TRANSITION_COST;
        } else {
            const dx = from.x - to.x;
            const dy = from.y - to.y;
            cost = Math.round(Math.sqrt(dx * dx + dy * dy));
            if (cost < 1) cost = 1;
        }

        return { ...edge, cost };
    });
}